# Generated by Django 3.1.2 on 2020-11-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kioskdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contents',
            name='goods_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer_bill',
            name='goods_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer_bill',
            name='goods_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer_bill',
            name='order_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer_bill',
            name='order_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='customer_bill',
            name='payment',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order_bill',
            name='goods_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order_bill',
            name='order_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order_bill',
            name='order_time',
            field=models.DateTimeField(),
        ),
    ]
