# Generated by Django 3.1.2 on 2020-11-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=50)),
                ('goods_price', models.IntegerField()),
                ('goods_origin', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='customer_bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('order_time', models.DateTimeField()),
                ('goods_name', models.CharField(max_length=50)),
                ('goods_price', models.IntegerField()),
                ('goods_count', models.IntegerField()),
                ('payment', models.IntegerField()),
                ('payment_method', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='order_bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('order_time', models.DateTimeField()),
                ('goods_id', models.CharField(max_length=50)),
                ('goods_name', models.CharField(max_length=50)),
                ('goods_count', models.IntegerField()),
            ],
        ),
    ]
