# Generated by Django 3.1.3 on 2020-11-07 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0002_auto_20201106_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='content',
            name='goods_origin',
        ),
        migrations.RemoveField(
            model_name='customer_bill',
            name='goods_count',
        ),
        migrations.RemoveField(
            model_name='customer_bill',
            name='goods_name',
        ),
        migrations.RemoveField(
            model_name='customer_bill',
            name='goods_price',
        ),
        migrations.RemoveField(
            model_name='customer_bill',
            name='order_time',
        ),
        migrations.RemoveField(
            model_name='order_bill',
            name='goods_name',
        ),
        migrations.RemoveField(
            model_name='order_bill',
            name='order_time',
        ),
        migrations.AlterField(
            model_name='order_bill',
            name='goods_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosk.content'),
        ),
        migrations.AlterField(
            model_name='customer_bill',
            name='order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kiosk.order_time'),
        ),
        migrations.AlterField(
            model_name='order_bill',
            name='order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kiosk.order_time'),
        ),
    ]
